SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_SPEED_BOOST = 1.2
FPS = 60

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOT_BASE_SPEED = 0.4

ASTEROID_COLOUR = "#705116"
PLAYER_COLOUR = "#264afc"
LASER_COLOUR = "#ff3526"

LASER_SPEED = 500
LASER_RADIUS = 5

POWERUP_RADIUS = 10
POWERUP_PIERCE_COLOUR = "#dde000"
POWERUP_SPEEDSHOT_COLOUR = "#00e6b8"
POWERUP_MULTISHOT_COLOUR = "#d907c0"
POWERUP_SHIELD_COLOUR = "#008a07"

POWERUP_CHANCE = 20
POWERUP_SPEEDSHOT_FACTOR = 0.5
POWERUP_DURATION = 15
POWERUP_MULTISHOT_ANGLE = 10